### PR TITLE
msmtpq: Fix removing all queue mail files after sending.

### PR DESCRIPTION
**Pull request by flyinggreenfrog**

### CODE REVIEW

**Comment by marlam** [comment]
Hi, this was already fixed in commit c78f24347ec996c7a3830b48403bf3736afca071 on April 19. I will release 1.8.9 soon.

**Comment by flyinggreenfrog** [comment]
Hi.

Mentioned commit c78f24347ec996c7a3830b48403bf3736afca071 was fixing it in line 293 in function `send_queued_mail()`. My commit was fixing the similar problem in line 504 in function `send_mail()`.

If I check current master, line 504 is still `'rm' -f "${FQP}.*"`, but should be `rm' -f "${FQP}".*`

**Comment by marlam** [comment]
You are right, I confused these two lines. Sorry. Unfortunately I already released 1.8.9 with the partial fix, but I replaced that with 1.8.10 immediately.

**Comment by flyinggreenfrog** [comment]
Thanks for quick reaction and releasing fixed version.

**Pull request closed without merging**
